/* jslint node:true */
module.exports = {
	"ON_JOB_CHANGE"		: "ONJOBCHANGE",
	"ON_JOB_LOADED"		: "ONJOBLOADED",
	"ON_JOB_FAILED"		: "ONJOBFAILED",
	"ON_JOB_KILL"		: "ONJOBKILL",
	"ON_JOB_STARTED"	: "ONJOBSTARTED",
	"ON_JOB_DATAFETCH"	: "ONJOBDATAFETCH",
	"ON_JOB_COMPILED"	: "ONJOBCOMPILED",
	"ON_JOB_DUMPED"		: "ONJOBDUMPED",
	"ON_JOB_PERSIST"	: "ONJOBPERSIST",
	"ON_JOB_PERSISTED"	: "ONJOBPERSISTED",
	"ON_JOB_CLEANED"	: "ONJOBCLEANED",
	"ON_JOB_BULKED"		: "ONJOBBULKED",
	"ON_JOB_FINISHED"	: "ONJOBFINISHED",
	"ON_JOB_DISCONNECT" : "ONJOBDISCONNECT",
	"ON_JOB_CLOSE" 		: "ONJOBCLOSE",
	"ON_JOB_ERROR" 		: "ONJOBERROR"
};